FROM bellsoft/liberica-openjdk-alpine:21

WORKDIR /app

COPY /target/*.jar ./app.jar

EXPOSE 8001

RUN apk add --no-cache curl
RUN mkdir -p /app/libs
RUN curl -L -o /app/libs/opentelemetry-javaagent.jar \
    https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.13.3/opentelemetry-javaagent.jar \
    && chmod 644 /app/libs/opentelemetry-javaagent.jar 

ENTRYPOINT ["java", "-javaagent:/app/libs/opentelemetry-javaagent.jar", "-jar", "app.jar"]