spring:
  application:
    name: payment-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest
  config:
      import:
        ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
server:
  port: 8070
  
eureka:
    client:
      register-with-eureka: true # Không đăng ký chính nó như một client
      fetch-registry: true # Không lấy registry từ server khác
      service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true # Use IP address instead of hostname
        instance-id: ${spring.application.name}:${server.port} # Unique instance ID
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      shutdown:
        access: unrestricted
      health:
        probes:
          enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true 
 
logging: 
  level:
    iuh:
      fit:
        se: DEBUG