global:
  scrape_interval: 15s  
  scrape_timeout: 10s   
  evaluation_interval: "5s" #inside dashboard
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: 'test-service'
    metrics_path: /actuator/prometheus
    honor_labels: false
    honor_timestamps: true
    scheme: http
    static_configs:
      - targets: ['test-service:8180']