spring:
  application:
    name: order-service
  config:
    import:
      ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/order-service}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
      
server:
  port: 8004

eureka:
  client:
    register-with-eureka: true # Không đăng ký chính nó như một client
    fetch-registry: true # Không lấy registry từ server khác
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
      prefer-ip-address: true # Use IP address instead of hostname
      instance-id: ${spring.application.name}:${server.port} # Unique instance ID  

info:
  app:
    name: "review-service"
    description: "Review service for Cloning shopee"
    version: "1.0.0"