spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hegoplay/config-NOW-Project.git
          clone-on-start: true
          default-label: main
          # Nếu repo private, thêm username và password
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
      enabled: true

server:
  port: 8888