spring:
  application:
    name: voucher-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27020/voucher-service}
      database: ${SPRING_DATA_MONGODB_DATABASE:voucher-service}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false 
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

      
eureka:
  client:
    register-with-eureka: true # Không đăng ký chính nó như một client
    fetch-registry: true # Không lấy registry từ server khác
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
      prefer-ip-address: true # Use IP address instead of hostname
      instance-id: ${spring.application.name}:${server.port} # Unique instance ID  

server:
  port: 8005


